In [1]:
import pandas as pd
import numpy as np

## Getting started

### Create a dataframe:

In [2]:
my_dataset = {
  'students': ["John", "Mary", "Kiril"],
  'grades': [88, 70, 99],
  'scores': ('B+', 'C-', 'A+'),
}

my_df = pd.DataFrame(my_dataset)
my_df

  students  grades scores
0     John      88     B+
1     Mary      70     C-
2    Kiril      99     A+

# Series

A Series is a column-vector. It is an array of individual entries, each of which has a certain value.

In [3]:
ages = pd.Series([18, 35, 42], name="Age")
ages

0    18
1    35
2    42
Name: Age, dtype: int64

In [4]:
#This is label-based slicing, but in Pandas, slices are end-exclusive when using integer positions (just like Python lists).
#It takes rows from index 1 up to (not including) index 2.

print(ages[1:2])

#.iloc means integer-location based indexing only!
# iloc[1:2] also takes rows at positions 1 up to (not including) 2.

ages.iloc[1:2]
#ages.loc[1:2]

1    35
Name: Age, dtype: int64

1    35
Name: Age, dtype: int64

In [5]:
#A plain Python list with mixed types: integers and a string
array = [1, 5, 'hello', 4, -10]

col_vec = pd.Series(array, name="Something")
col_vec

# Left column = the index (default = 0,1,2,3,4).

# Right column = the values from your list.

# Name: Something → the column name you gave.

# dtype: object → because of mixed types.

0        1
1        5
2    hello
3        4
4      -10
Name: Something, dtype: object

In [6]:
#col_vec[1:4]

col_vec.loc[1:4]

1        5
2    hello
3        4
4      -10
Name: Something, dtype: object

In [7]:
array = [1, 5, 'hello', 4, -10]
col_vec = pd.Series(array, 
                    index=['a','b','c','d','e'])
col_vec

a        1
b        5
c    hello
d        4
e      -10
dtype: object

In [8]:
col_vec['c']

#slicing with step 2 - take every second element after b
#col_vec['b'::2]

#returns everything except the first row
#col_vec.iloc[1:]

#return everything starting with index c
#col_vec.loc['c':]

#col_vec.loc[['c','a']]
#col_vec.loc['c':]

'hello'

# iloc: → Integer-location based indexing ("I want the row/column at position i")
## Always uses zero-based integer positions (like plain Python lists)

___________________________________________________________________________________

# loc: → Label-based indexing ("I want the row/column with label L")
## Always uses labels of the index (row/column names)

In [9]:
grades = {"John": 88, "Mary": 70, "Kiril": 99}
my_ser = pd.Series(grades)
my_ser

John     88
Mary     70
Kiril    99
dtype: int64

In [10]:
my_ser = pd.Series(grades, index = ["John", "Mary"])
my_ser

John    88
Mary    70
dtype: int64

In [11]:
grades = {"John": 88, "Mary": 70, "Kiril": 99, "Nadia": 90}
other_ser = pd.Series(grades)
other_ser

John     88
Mary     70
Kiril    99
Nadia    90
dtype: int64

Pandas (and NumPy) use NaN to represent missing or undefined data

In [12]:
my_ser+other_ser

John     176.0
Kiril      NaN
Mary     140.0
Nadia      NaN
dtype: float64

In [13]:
series1 = pd.Series([1, 2, 3])
series2 = pd.Series([4, 5, 6])

series1 + series2

0    5
1    7
2    9
dtype: int64

# Dataframes

A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.

### Toy example 1: DataFrame from a dictionary

In [14]:
data = {
    'Date': ['2025-01-10', '2025-01-12', '2025-01-13', '2025-01-02', '2025-01-02', '2025-01-03', '2024-05-03', '2024-05-03'],
    'Item': ['Apple', 'Banana', 'Orange', 'Apple', 'Banana', 'Orange', 'Apple', 'Orange'],
    'Units Sold': [30, 21, 15, 40, 34, 20, 45, 25],
    'Price Per Unit': [1.0, 0.5, 0.75, 1.0, 0.5, 0.75, 1.0, 0.75],
    'Salesperson': ['John', 'John', 'John', 'Alice', 'Alice', 'John', 'Alice', 'John']
}

df = pd.DataFrame(data)

# Display the DataFrame
df

         Date    Item  Units Sold  Price Per Unit Salesperson
0  2025-01-10   Apple          30            1.00        John
1  2025-01-12  Banana          21            0.50        John
2  2025-01-13  Orange          15            0.75        John
3  2025-01-02   Apple          40            1.00       Alice
4  2025-01-02  Banana          34            0.50       Alice
5  2025-01-03  Orange          20            0.75        John
6  2024-05-03   Apple          45            1.00       Alice
7  2024-05-03  Orange          25            0.75        John

### Toy example 2: DataFrame from a matrix

In [15]:
toy_matrix = [[1,2,3,4],
              [4,5,6,7],
              [7,8,9,0],
              [1,1,2,5],
              [0,0,9,6],
              [0,0,10,3]
             ]
df = pd.DataFrame(toy_matrix, columns=["A", "B", "C", "D"],index=["a","b","c","d","e","f"],dtype=int)

In [16]:
display(df)
print(df)
df

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

### Summary of the basic information about the DataFrame

In [17]:
df.shape

(6, 4)

In [18]:
df.size

24

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, a to f
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      int64
 1   B       6 non-null      int64
 2   C       6 non-null      int64
 3   D       6 non-null      int64
dtypes: int64(4)
memory usage: 240.0+ bytes

In [20]:
df.describe()
# x% percentile is the value below which x% of the data points fall

              A         B          C         D
count  6.000000  6.000000   6.000000  6.000000
mean   2.166667  2.666667   6.500000  4.166667
std    2.786874  3.204164   3.391165  2.483277
min    0.000000  0.000000   2.000000  0.000000
25%    0.250000  0.250000   3.750000  3.250000
50%    1.000000  1.500000   7.500000  4.500000
75%    3.250000  4.250000   9.000000  5.750000
max    7.000000  8.000000  10.000000  7.000000

In [21]:
df.nunique()
# Return the number of unique values in each column of a DataFrame

A    4
B    5
C    5
D    6
dtype: int64

### Head, Tail, and Sample

In [22]:
df.head(2)

   A  B  C  D
a  1  2  3  4
b  4  5  6  7

In [23]:
df.tail(3)

   A  B   C  D
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

In [24]:
df.sample(5, random_state=0)

   A  B   C  D
f  0  0  10  3
c  7  8   9  0
b  4  5   6  7
d  1  1   2  5
a  1  2   3  4

### Getting indices (names) of columns

In [25]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

### Getting indices of rows

In [26]:
# df.rows does NOT exist
# use df.index instead
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

## Accessing rows, columns and elements of a DataFrame

### Columns

- You can directly access columns using
    - Its name
    - Or a list/array of names
- You CANNOT use a range!

In [27]:
df['B']

a    2
b    5
c    8
d    1
e    0
f    0
Name: B, dtype: int64

In [28]:
# still possible to apply Python slicing accessing column names
df[df.columns[1:3]]

   B   C
a  2   3
b  5   6
c  8   9
d  1   2
e  0   9
f  0  10

In [29]:
df[['B','A']]

   B  A
a  2  1
b  5  4
c  8  7
d  1  1
e  0  0
f  0  0

### Rows 

- You can directly access rows using a range
- An individual row CANNOT be accessed in such a way!

In [30]:
df['a':'c']
# but you cannot access a row / rows doing df['a'] or df[['a']] or df[['a','b']]

   A  B  C  D
a  1  2  3  4
b  4  5  6  7
c  7  8  9  0

### Rows and Columns

In [31]:
df['b':][["A","C"]]

   A   C
b  4   6
c  7   9
d  1   2
e  0   9
f  0  10

In [32]:
# :: (Stop): Since the middle value is empty,
# it will continue through to the end of the DataFrame.

df['b'::2][["A","C"]]

   A   C
b  4   6
d  1   2
f  0  10

### `loc` & `iloc` 
Usage: `loc[rows]` or `loc[rows, columns]`

Usage: `iloc[rows]` or `iloc[rows, columns]`

In [33]:
df

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

### Rows

In [34]:
df.loc['b']
df.iloc[1]

A    4
B    5
C    6
D    7
Name: b, dtype: int64

In [35]:
df.loc['b':]
df.iloc[1:]

   A  B   C  D
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

In [36]:
df.loc[['b','a','f']]
df.iloc[[1,0,5]]

   A  B   C  D
b  4  5   6  7
a  1  2   3  4
f  0  0  10  3

### Columns

In [37]:
df

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

In [38]:
# : means all rows and select column B values
df.loc[:,'B']
df.iloc[:,1]

a    2
b    5
c    8
d    1
e    0
f    0
Name: B, dtype: int64

In [39]:
df.loc[:,['B','A']]
df.iloc[:,[1,0]]

   B  A
a  2  1
b  5  4
c  8  7
d  1  1
e  0  0
f  0  0

In [40]:
df.loc[:,'B'::2]
df.iloc[:,1::2]

   B  D
a  2  4
b  5  7
c  8  0
d  1  5
e  0  6
f  0  3

### Row and Columns

In [41]:
df.loc['b':'e', ["A", "C"]]

   A  C
b  4  6
c  7  9
d  1  2
e  0  9

In [42]:
df.iloc[3:5, 1:]

   B  C  D
d  1  2  5
e  0  9  6

### Individual Elements

In [43]:
df

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

In [44]:
df.loc['a', 'A']

# In Pandas, .at is a specialized accessor used for label-based indexing
# to access or modify a single scalar value in a DataFrame. It is the high-speed counterpart to .loc
df.at['a', 'A']

np.int64(1)

In [45]:
df.iloc[0,0]
df.iat[0,0]

np.int64(1)

### Difference in indexing between loc and iloc

In [46]:
df

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

In [47]:
df_reset = df.reset_index(drop=True)  # drop=True removes the old index
df_reset

   A  B   C  D
0  1  2   3  4
1  4  5   6  7
2  7  8   9  0
3  1  1   2  5
4  0  0   9  6
5  0  0  10  3

In [48]:
df_reset.loc[2:5]

   A  B   C  D
2  7  8   9  0
3  1  1   2  5
4  0  0   9  6
5  0  0  10  3

In [49]:
df_reset.iloc[2:5]

   A  B  C  D
2  7  8  9  0
3  1  1  2  5
4  0  0  9  6

## Sorting

In [50]:
df

   A  B   C  D
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0
d  1  1   2  5
e  0  0   9  6
f  0  0  10  3

In [51]:
# axis - 0 for row-wise, 1 for column-wise
df.sort_index(axis=1, ascending=False)

   D   C  B  A
a  4   3  2  1
b  7   6  5  4
c  0   9  8  7
d  5   2  1  1
e  6   9  0  0
f  3  10  0  0

In [52]:
df.sort_values(["A", "B", "D"], ascending=True)

   A  B   C  D
f  0  0  10  3
e  0  0   9  6
d  1  1   2  5
a  1  2   3  4
b  4  5   6  7
c  7  8   9  0

## Adding, Removing, Renaming rows and columns

### Adding a row

In [53]:
df.loc['w'] = [3, 4, 10, 999]
df

   A  B   C    D
a  1  2   3    4
b  4  5   6    7
c  7  8   9    0
d  1  1   2    5
e  0  0   9    6
f  0  0  10    3
w  3  4  10  999

In [54]:
new_row = pd.DataFrame({'A': [10], 'B': [30], 'C' : [45], 'D' : [45]}, index=['v']) # Just another dataframe

df = pd.concat([df, new_row])

df

    A   B   C    D
a   1   2   3    4
b   4   5   6    7
c   7   8   9    0
d   1   1   2    5
e   0   0   9    6
f   0   0  10    3
w   3   4  10  999
v  10  30  45   45

### Adding a column

#### Adding by broadcasting

In [55]:
df['price'] = 10
df

    A   B   C    D  price
a   1   2   3    4     10
b   4   5   6    7     10
c   7   8   9    0     10
d   1   1   2    5     10
e   0   0   9    6     10
f   0   0  10    3     10
w   3   4  10  999     10
v  10  30  45   45     10

In [56]:
df["new"] = df["A"] * df["B"]
df

    A   B   C    D  price  new
a   1   2   3    4     10    2
b   4   5   6    7     10   20
c   7   8   9    0     10   56
d   1   1   2    5     10    1
e   0   0   9    6     10    0
f   0   0  10    3     10    0
w   3   4  10  999     10   12
v  10  30  45   45     10  300

#### Adding with `np.where()`

In [57]:
df['new_price'] = np.where(df['A'] >= 2, 5, 3) 
df

# condition → a boolean array | 2
# value_if_true → assigned where the condition is True | 5
# value_if_false → assigned where the condition is False | 3

    A   B   C    D  price  new  new_price
a   1   2   3    4     10    2          3
b   4   5   6    7     10   20          5
c   7   8   9    0     10   56          5
d   1   1   2    5     10    1          3
e   0   0   9    6     10    0          3
f   0   0  10    3     10    0          3
w   3   4  10  999     10   12          5
v  10  30  45   45     10  300          5

#### Adding with `.apply()`

In [58]:
# .apply() applies a function to each element of the column 'D'
df['some_category'] = df['D'].apply(lambda x: 'Short' if x < 4 else ('Average' if x < 5 else 'Tall'))
df

    A   B   C    D  price  new  new_price some_category
a   1   2   3    4     10    2          3       Average
b   4   5   6    7     10   20          5          Tall
c   7   8   9    0     10   56          5         Short
d   1   1   2    5     10    1          3          Tall
e   0   0   9    6     10    0          3          Tall
f   0   0  10    3     10    0          3         Short
w   3   4  10  999     10   12          5          Tall
v  10  30  45   45     10  300          5          Tall

In [59]:
def categorize(row):
    if row['C'] < 3 and row['D'] < 5:
        return 'Light'
    elif row['C'] < 5 or row['D'] <= 6:
        return 'Middle'
    else:
        return 'Heavy'
    
df['one more category'] = df.apply(categorize, axis=1)
df

    A   B   C    D  price  new  new_price some_category one more category
a   1   2   3    4     10    2          3       Average            Middle
b   4   5   6    7     10   20          5          Tall             Heavy
c   7   8   9    0     10   56          5         Short            Middle
d   1   1   2    5     10    1          3          Tall            Middle
e   0   0   9    6     10    0          3          Tall            Middle
f   0   0  10    3     10    0          3         Short            Middle
w   3   4  10  999     10   12          5          Tall             Heavy
v  10  30  45   45     10  300          5          Tall             Heavy

In [60]:
def random_name(_):
    first_names = ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Helen']
    last_names = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Garcia']
    return f"{np.random.choice(first_names)} {np.random.choice(last_names)}"

df['Name'] = df.apply(random_name, axis=1)

df

,A,B,C,D,price,new,new_price,some_category,one more category,Name
a,1,2,3,4,10,2,3,Average,Middle,David Jones
b,4,5,6,7,10,20,5,Tall,Heavy,Emma Williams
c,7,8,9,0,10,56,5,Short,Middle,Emma Williams
d,1,1,2,5,10,1,3,Tall,Middle,Frank Brown
e,0,0,9,6,10,0,3,Tall,Middle,Frank Garcia
f,0,0,10,3,10,0,3,Short,Middle,Alice Johnson
w,3,4,10,999,10,12,5,Tall,Heavy,Helen Davis
v,10,30,45,45,10,300,5,Tall,Heavy,Helen Johnson

In [61]:
df['First Name'] = df['Name'].str.split(' ').str[0]
df

,A,B,C,D,price,new,new_price,some_category,one more category,Name,First Name
a,1,2,3,4,10,2,3,Average,Middle,David Jones,David
b,4,5,6,7,10,20,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,10,56,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,10,1,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,10,0,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,10,0,3,Short,Middle,Alice Johnson,Alice
w,3,4,10,999,10,12,5,Tall,Heavy,Helen Davis,Helen
v,10,30,45,45,10,300,5,Tall,Heavy,Helen Johnson,Helen

### Removing a row

In [62]:
df.drop(index=['v'], inplace=True, errors='ignore')  
df = df.drop(index=['v'], errors='ignore')
df

,A,B,C,D,price,new,new_price,some_category,one more category,Name,First Name
a,1,2,3,4,10,2,3,Average,Middle,David Jones,David
b,4,5,6,7,10,20,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,10,56,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,10,1,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,10,0,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,10,0,3,Short,Middle,Alice Johnson,Alice
w,3,4,10,999,10,12,5,Tall,Heavy,Helen Davis,Helen

### Removing a column

In [63]:
df.drop(columns=['price'], inplace=True, errors='ignore')
df = df.drop(columns=['price'], errors='ignore')
df

,A,B,C,D,new,new_price,some_category,one more category,Name,First Name
a,1,2,3,4,2,3,Average,Middle,David Jones,David
b,4,5,6,7,20,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,0,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0,3,Short,Middle,Alice Johnson,Alice
w,3,4,10,999,12,5,Tall,Heavy,Helen Davis,Helen

In [64]:
if 'price' in df.columns:
    df.drop(columns=['price'], inplace=True)

### Renaming a row

In [65]:
df.rename(index={'w': 'x'}, inplace=True)
df

,A,B,C,D,new,new_price,some_category,one more category,Name,First Name
a,1,2,3,4,2,3,Average,Middle,David Jones,David
b,4,5,6,7,20,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,0,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,12,5,Tall,Heavy,Helen Davis,Helen

### Renaming a column

In [66]:
df.rename(columns={'new_price': 'price'}, inplace=True)
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,2,3,Average,Middle,David Jones,David
b,4,5,6,7,20,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,0,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,12,5,Tall,Heavy,Helen Davis,Helen

## Filtering rows

In [67]:
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,2,3,Average,Middle,David Jones,David
b,4,5,6,7,20,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,0,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,12,5,Tall,Heavy,Helen Davis,Helen

### Filtering with condition(s)

In [68]:
df.loc[df["A"] > 1]
df.loc[df["A"] > 1,:]
df[df["A"] > 1] # Without .loc

,A,B,C,D,new,price,some_category,one more category,Name,First Name
b,4,5,6,7,20,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56,5,Short,Middle,Emma Williams,Emma
x,3,4,10,999,12,5,Tall,Heavy,Helen Davis,Helen

In [69]:
df.loc[df["A"] > 1, ["C","A", "one more category"]]
df[df["A"] > 1][["C","A","one more category"]] # Without .loc

    C  A one more category
b   6  4             Heavy
c   9  7            Middle
x  10  3             Heavy

In [70]:
df[(df['A'] < 3) & (df['B'] == 0)]

,A,B,C,D,new,price,some_category,one more category,Name,First Name
e,0,0,9,6,0,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0,3,Short,Middle,Alice Johnson,Alice

### Filtering `nan`'s

In [71]:
# Let's have some NaN values in our dataframe


# Number of random NaNs to introduce
num_nans = 5  

row_indices = np.random.choice(df.index, size=num_nans)
col_indices = np.random.choice(df.columns, size=1)

df.loc[row_indices, col_indices] = np.nan
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [72]:
df[df['C'].notna()]

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [73]:
# Keep only rows that have any missing values
df[df.isna().any(axis=1)]

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [74]:
# Keep only rows that have no missing values
df[df.notna().all(axis=1)]

,A,B,C,D,new,price,some_category,one more category,Name,First Name
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice

### String filtering

In [75]:
df[df['some_category'].str.contains("tall", case=False)]
# case = False -> tell pandas to ignore
# whether the letters are uppercase or lowercase

,A,B,C,D,new,price,some_category,one more category,Name,First Name
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [76]:
# Regex syntax!
df[df['some_category'].str.contains('tall|short', case=False)]

,A,B,C,D,new,price,some_category,one more category,Name,First Name
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [77]:
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [78]:
df[df['A'].isin([2,3,5,7]) & (df['some_category'].str.lower().str.startswith("sh"))]

,A,B,C,D,new,price,some_category,one more category,Name,First Name
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma

## Filtering columns

In [79]:
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

### Selecting specific columns

In [80]:
df[['A', 'Name']]

   A           Name
a  1    David Jones
b  4  Emma Williams
c  7  Emma Williams
d  1    Frank Brown
e  0   Frank Garcia
f  0  Alice Johnson
x  3    Helen Davis

### Dropping columns

In [81]:
df.drop(columns=['A', 'B'])

,C,D,new,price,some_category,one more category,Name,First Name
a,3,4,NaN,3,Average,Middle,David Jones,David
b,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

### Based on data type

In [82]:
df.select_dtypes(include=['number'])

   A  B   C    D   new  price
a  1  2   3    4   NaN      3
b  4  5   6    7  20.0      5
c  7  8   9    0  56.0      5
d  1  1   2    5   1.0      3
e  0  0   9    6   NaN      3
f  0  0  10    3   0.0      3
x  3  4  10  999   NaN      5

### By name pattern

In [83]:
df.filter(items=['A','C'], axis=1)

   A   C
a  1   3
b  4   6
c  7   9
d  1   2
e  0   9
f  0  10
x  3  10

In [84]:
df.filter(regex='A|B|C', axis=1)

   A  B   C
a  1  2   3
b  4  5   6
c  7  8   9
d  1  1   2
e  0  0   9
f  0  0  10
x  3  4  10

### Filtering `nan`'s

In [85]:
# Keep columns with any missing values
df.loc[:, df.isna().any()]

    new
a   NaN
b  20.0
c  56.0
d   1.0
e   NaN
f   0.0
x   NaN

In [86]:
# Keep only columns that have no missing values
df.loc[:, df.notna().all()]

,A,B,C,D,price,some_category,one more category,Name,First Name
a,1,2,3,4,3,Average,Middle,David Jones,David
b,4,5,6,7,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,5,Tall,Heavy,Helen Davis,Helen

## Handling Null Values

In [87]:
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [88]:
df['price'] = df['price'].fillna(df['price'].mean())
# Make sure to set this to your 'price' column if you want these changes to stick 
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [89]:
df['C'] = df['C'].interpolate()
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [90]:
df = df.dropna(subset=['C']) 
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

## Grouping data

`.groupby('some_category')` groups all rows having the same attributes (as specified in by parameter) into separate data frames.

After the groupby, you need an aggregate function to summarize data in each subframe.

You may do it in 2 ways:

In [91]:
# In each subframe, take the `price` column and summarize it
# using the `sum` function from the result
df.groupby(['some_category'])['price'].sum()

some_category
Average     3
Short       8
Tall       16
Name: price, dtype: int64

In [92]:
# In each subframe, apply the `sum` function to all numeric
# columns then extract the `price` column
df.groupby(['some_category']).sum()['price']

some_category
Average     3
Short       8
Tall       16
Name: price, dtype: int64

## Pivot Tables

In [93]:
df

,A,B,C,D,new,price,some_category,one more category,Name,First Name
a,1,2,3,4,NaN,3,Average,Middle,David Jones,David
b,4,5,6,7,20.0,5,Tall,Heavy,Emma Williams,Emma
c,7,8,9,0,56.0,5,Short,Middle,Emma Williams,Emma
d,1,1,2,5,1.0,3,Tall,Middle,Frank Brown,Frank
e,0,0,9,6,NaN,3,Tall,Middle,Frank Garcia,Frank
f,0,0,10,3,0.0,3,Short,Middle,Alice Johnson,Alice
x,3,4,10,999,NaN,5,Tall,Heavy,Helen Davis,Helen

In [94]:
# Pivot Table: Think of it as a way to group your data by one or more keys and then calculate a statistic (like the mean, sum, or count)
# for each group, organized into a clean, 2D grid

df.pivot_table(index='some_category', columns='one more category', values='price', aggfunc='mean')

one more category  Heavy  Middle
some_category
Average              NaN     3.0
Short                NaN     4.0
Tall                 5.0     3.0

In [95]:
df.pivot_table(index='some_category', columns='one more category', values='price', aggfunc=['sum', 'mean'], fill_value=0)

                    sum         mean
one more category Heavy Middle Heavy Middle
some_category
Average               0      3   0.0    3.0
Short                 0      8   0.0    4.0
Tall                 10      6   5.0    3.0