**1.** Import pandas under the alias `pd`.

In [421]:
import pandas as pd

**2.** Print the version of pandas that has been imported.

In [422]:
print(pd.__version__)

2.3.1

**3.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [423]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

**4.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [424]:
df.describe()

            age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**5.** Return the first 3 rows of the DataFrame `df`.

In [425]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**6.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [426]:
Q6_df = df[['animal', 'age']]
Q6_df

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**7.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [427]:
Q7_df = Q6_df.iloc[[ 2, 3, 7], :]
Q7_df

  animal  age
c  snake  0.5
d    dog  NaN
h    cat  NaN

**8.** Select only the rows where the number of visits is greater than 1.

In [428]:
Q8_df = df[df['visits'] > 1]
Q8_df

  animal  age  visits priority
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
i    dog  7.0       2       no

**9.** Select the rows where the age is missing, i.e. it is `NaN`.

In [429]:
Q9_df = df[df['age'].isnull()]
Q9_df

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**10.** Select the rows where the animal is a cat *and* the age is less than 3.

In [430]:
Q10_df = df[(df['age'] < 3) & (df['animal'] == 'cat')]
Q10_df

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**11.** Select the rows the age is between 2 and 4 (inclusive).

In [431]:
Q11_df = df[(df['age'] > 2) & (df['age'] < 4)]
Q11_df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no

**12.** Change the age in row 'f' to 1.5.

In [432]:
df.loc['f', 'age'] = 1.5                               
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**13.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [433]:
df['visits'].sum()

np.int64(19)

**14.** Calculate the mean age for each different animal in `df`.

In [434]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**15.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [435]:
df.loc['k'] = ['capybara', 137, 0, 'no']
df

     animal    age  visits priority
a       cat    2.5       1      yes
b       cat    3.0       3      yes
c     snake    0.5       2       no
d       dog    NaN       3      yes
e       dog    5.0       2       no
f       cat    1.5       3       no
g     snake    4.5       1       no
h       cat    NaN       1      yes
i       dog    7.0       2       no
j       dog    3.0       1       no
k  capybara  137.0       0       no

In [436]:
df.drop('k', inplace=True)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**16.** Count the number of each type of animal in `df`.

In [437]:
df.groupby('animal').size()

animal
cat      4
dog      4
snake    2
dtype: int64

**17.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [438]:
df.sort_values(by=['age'], ascending=False)

  animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
b    cat  3.0       3      yes
j    dog  3.0       1       no
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [439]:
df.sort_values(by=['visits'], ascending=True)

  animal  age  visits priority
a    cat  2.5       1      yes
h    cat  NaN       1      yes
g  snake  4.5       1       no
j    dog  3.0       1       no
e    dog  5.0       2       no
c  snake  0.5       2       no
i    dog  7.0       2       no
b    cat  3.0       3      yes
f    cat  1.5       3       no
d    dog  NaN       3      yes

**18.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [440]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  1.5       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

**19.** In the 'animal' column, change the 'snake' entries to 'python'.

In [441]:
df['animal'] = df['animal'].replace({'snake': 'python'})
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  1.5       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False

**20.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [442]:
df.pivot_table(index="animal", columns="visits", values="age", aggfunc="mean")

visits    1    2     3
animal
cat     2.5  NaN  2.25
dog     3.0  6.0   NaN
python  4.5  0.5   NaN

**21.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [443]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df.sub(df.mean(axis=1), axis=0)

          0         1         2
0  0.129907 -0.221345  0.091439
1 -0.164437 -0.017004  0.181441
2  0.310749  0.117422 -0.428171
3  0.009484 -0.044009  0.034525
4 -0.167205  0.350528 -0.183323

**22.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [444]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
len(df.drop_duplicates())

4

**23.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

In [445]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [446]:
df["FlightNumber"] = (
    df["FlightNumber"].interpolate().astype(int)
)  # or: df['FlightNumber'] = df['FlightNumber'].ffill() + df.groupby(df['FlightNumber'].notnull().cumsum()).cumcount() * 10
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

**24.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame.

In [447]:
temp = df["From_To"].str.split("_", expand=True)
temp.columns = ["From", "To"]
temp

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**25.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [448]:
temp["From"] = temp["From"].str.title()
temp["To"] = temp["To"].str.title()
temp

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**26.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

In [449]:
df = df.drop("From_To", axis=1).join(temp)
df

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London

**27**. In the **Airline** column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [450]:
df["Airline"] = df["Airline"].str.extract(r"([a-zA-Z\s]+)", expand=False).str.strip()
df

   FlightNumber  RecentDelays          Airline      From         To
0         10045      [23, 47]              KLM    London      Paris
1         10055            []       Air France    Madrid      Milan
2         10065  [24, 43, 87]  British Airways    London  Stockholm
3         10075          [13]       Air France  Budapest      Paris
4         10085      [67, 32]        Swiss Air  Brussels     London

**28**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [451]:
delays = df["RecentDelays"].apply(pd.Series)
delays.columns = [f"delay_{i+1}" for i in range(delays.shape[1])]
df = df.drop("RecentDelays", axis=1).join(delays)
df

,FlightNumber,Airline,From,To,delay_1,delay_2,delay_3
0,10045,KLM,London,Paris,23.0,47.0,NaN
1,10055,Air France,Madrid,Milan,NaN,NaN,NaN
2,10065,British Airways,London,Stockholm,24.0,43.0,87.0
3,10075,Air France,Budapest,Paris,13.0,NaN,NaN
4,10085,Swiss Air,Brussels,London,67.0,32.0,NaN